git:
  depth: 1
language: node_js
node_js:
  - "stable"
  - "lts/*"
cache:
  directories:
    - "node_modules"
before_install:
  - npm set progress false
after_success:
  - npm i --save-dev coveralls
  - npm run report-coveralls
